# action.yml
apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: 'platform-action-gke-deployment'
description: 'deploying an application on GKE Cluster'
inputs:
  service-account:  # gcp service account
    description: 'service account'
    required: true
  key-file: # key file used for login
    description: 'key file for the service account'
    required: true
  project: 
    description: 'the name of the gcp project'
    required: true
  cluster-name: 
    description: 'the name of the gke cluster'
    required: true
  zone: 
    description: 'the zone of the gke cluster'
    required: true

runs:
  using: composite
  steps:
    - id: download-key-file
      uses: cloudbees-io/s3-download-object@v1
      name: Prepare env
      with:
        bucket-name: pyang-test-s3
        file-path: ./test.json
        s3-path: testCNP/test.json
    - id: login
      name: "login using service account and key file" 
      uses: docker://poseidon1979/gcloud-kubectl-image:latest
      run: |
        gcloud auth activate-service-account ${{ inputs.service-account }} --key-file=./test.json --project=${{ inputs.project }}; 
        gcloud container clusters get-credentials ${{ inputs.cluster-name }} --zone ${{ inputs.zone }} --project ${{ inputs.project }}; 
    - id: deploy
      uses: docker://poseidon1979/gcloud-kubectl-image:latest
      name: deploy
      run: |
        kubectl apply -f ./simple_java_app/myapp.yaml

